apiVersion: ec2.aws.upbound.io/v1beta1
kind: MainRouteTableAssociation
metadata:
  annotations:
    crossplane.io/composition-resource-name: mrt
    crossplane.io/external-create-pending: "2024-08-17T00:18:56Z"
    crossplane.io/external-create-succeeded: "2024-08-17T00:18:56Z"
    crossplane.io/external-name: rtbassoc-0f12faa8b2159c91d
  creationTimestamp: "2024-08-17T00:15:48Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-pg888
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 74422427-ef9c-4d2c-bee5-3a6cfef8684d
  resourceVersion: "468271"
  uid: 0f8ab476-3d7c-429b-8be9-b7102a13b390
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    routeTableId: rtb-0af6bc45f6642a988
    routeTableIdRef:
      name: configuration-aws-network-vbcgd
    routeTableIdSelector:
      matchControllerRef: true
    vpcId: vpc-0036481418bd747c0
    vpcIdRef:
      name: configuration-aws-network-6jtl4
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    id: rtbassoc-0f12faa8b2159c91d
    originalRouteTableId: rtb-067947173b61b13b2
    routeTableId: rtb-0af6bc45f6642a988
    vpcId: vpc-0036481418bd747c0
  conditions:
  - lastTransitionTime: "2024-08-17T12:54:31Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-17T00:19:57Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-17T00:18:57Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
