apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  annotations:
    crossplane.io/composition-resource-name: rta-us-west-2a-private
    crossplane.io/external-create-pending: "2024-08-17T00:19:56Z"
    crossplane.io/external-create-succeeded: "2024-08-17T00:19:57Z"
    crossplane.io/external-name: rtbassoc-0b3a4d9e590618d49
  creationTimestamp: "2024-08-17T00:15:48Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-stjtq
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 74422427-ef9c-4d2c-bee5-3a6cfef8684d
  resourceVersion: "464316"
  uid: 8171692b-0d0b-444e-a0e7-028e3785a295
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    routeTableId: rtb-0af6bc45f6642a988
    routeTableIdRef:
      name: configuration-aws-network-vbcgd
    routeTableIdSelector:
      matchControllerRef: true
    subnetId: subnet-0f9e3ba5869114d56
    subnetIdRef:
      name: configuration-aws-network-52h6d
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: private
        zone: us-west-2a
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    gatewayId: ""
    id: rtbassoc-0b3a4d9e590618d49
    routeTableId: rtb-0af6bc45f6642a988
    subnetId: subnet-0f9e3ba5869114d56
  conditions:
  - lastTransitionTime: "2024-08-17T09:52:57Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-17T00:20:57Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-17T00:19:57Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
