apiVersion: ec2.aws.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  annotations:
    crossplane.io/composition-resource-name: rta-us-west-2b-public
    crossplane.io/external-create-pending: "2024-08-17T00:19:56Z"
    crossplane.io/external-create-succeeded: "2024-08-17T00:19:57Z"
    crossplane.io/external-name: rtbassoc-0e6d534c10ca22a07
  creationTimestamp: "2024-08-17T00:15:48Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-pnvdg
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 74422427-ef9c-4d2c-bee5-3a6cfef8684d
  resourceVersion: "441919"
  uid: b81db4ba-0d29-4e30-ad60-5ba9114aac88
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-west-2
    routeTableId: rtb-0af6bc45f6642a988
    routeTableIdRef:
      name: configuration-aws-network-vbcgd
    routeTableIdSelector:
      matchControllerRef: true
    subnetId: subnet-063efc382573f60a7
    subnetIdRef:
      name: configuration-aws-network-gzzrb
    subnetIdSelector:
      matchControllerRef: true
      matchLabels:
        access: public
        zone: us-west-2b
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    gatewayId: ""
    id: rtbassoc-0e6d534c10ca22a07
    routeTableId: rtb-0af6bc45f6642a988
    subnetId: subnet-063efc382573f60a7
  conditions:
  - lastTransitionTime: "2024-08-17T00:19:57Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-17T00:19:58Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-17T00:19:57Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
