apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  annotations:
    crossplane.io/composition-resource-name: sgrp
    crossplane.io/external-create-pending: "2024-08-17T00:19:56Z"
    crossplane.io/external-create-succeeded: "2024-08-17T00:19:57Z"
    crossplane.io/external-name: sgrule-1899152031
  creationTimestamp: "2024-08-17T00:15:48Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-kq5th
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 74422427-ef9c-4d2c-bee5-3a6cfef8684d
  resourceVersion: "462830"
  uid: 6146b41c-43a3-4f2a-843a-da539876f176
spec:
  deletionPolicy: Delete
  forProvider:
    cidrBlocks:
    - 0.0.0.0/0
    description: Everywhere
    fromPort: 5432
    protocol: tcp
    region: us-west-2
    securityGroupId: sg-02c0692e10f650141
    securityGroupIdRef:
      name: configuration-aws-network-9m99r
    securityGroupIdSelector:
      matchControllerRef: true
    toPort: 5432
    type: ingress
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    cidrBlocks:
    - 0.0.0.0/0
    description: Everywhere
    fromPort: 5432
    id: sgrule-1899152031
    protocol: tcp
    securityGroupId: sg-02c0692e10f650141
    securityGroupRuleId: sgr-013fe2f417a9468f8
    self: false
    toPort: 5432
    type: ingress
  conditions:
  - lastTransitionTime: "2024-08-17T08:39:37Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-17T00:19:59Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-17T00:19:58Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
