apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  annotations:
    crossplane.io/composition-resource-name: sg
    crossplane.io/external-create-pending: "2024-08-17T00:18:55Z"
    crossplane.io/external-create-succeeded: "2024-08-17T00:18:55Z"
    crossplane.io/external-name: sg-02c0692e10f650141
  creationTimestamp: "2024-08-17T00:15:48Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-9m99r
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 74422427-ef9c-4d2c-bee5-3a6cfef8684d
  resourceVersion: "467920"
  uid: ca765704-0cfe-45e8-bfd2-698643437ca3
spec:
  deletionPolicy: Delete
  forProvider:
    description: Allow access to databases
    name: platform-ref-aws-cluster
    region: us-west-2
    tags:
      crossplane-kind: securitygroup.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-9m99r
      crossplane-providerconfig: default
    vpcId: vpc-0036481418bd747c0
    vpcIdRef:
      name: configuration-aws-network-6jtl4
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:123456789012:security-group/sg-02c0692e10f650141
    description: Allow access to databases
    id: sg-02c0692e10f650141
    ingress:
    - cidrBlocks:
      - 0.0.0.0/0
      description: Everywhere
      fromPort: 3306
      protocol: tcp
      self: false
      toPort: 3306
    - cidrBlocks:
      - 0.0.0.0/0
      description: Everywhere
      fromPort: 5432
      protocol: tcp
      self: false
      toPort: 5432
    name: platform-ref-aws-cluster
    ownerId: "123456789012"
    revokeRulesOnDelete: false
    tags:
      crossplane-kind: securitygroup.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-9m99r
      crossplane-providerconfig: default
    tagsAll:
      crossplane-kind: securitygroup.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-9m99r
      crossplane-providerconfig: default
    vpcId: vpc-0036481418bd747c0
  conditions:
  - lastTransitionTime: "2024-08-17T12:30:26Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-17T00:18:59Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-17T00:18:57Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
