apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  annotations:
    crossplane.io/composition-resource-name: subnet-us-west-2a-public
    crossplane.io/external-create-pending: "2024-08-17T00:18:55Z"
    crossplane.io/external-create-succeeded: "2024-08-17T00:18:55Z"
    crossplane.io/external-name: subnet-00ca6a5b1969198e5
  creationTimestamp: "2024-08-17T00:15:48Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 4
  labels:
    access: public
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
    zone: us-west-2a
  name: configuration-aws-network-phfgs
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 74422427-ef9c-4d2c-bee5-3a6cfef8684d
  resourceVersion: "465422"
  uid: e0118896-6816-49ca-a3fe-fd90b848596c
spec:
  deletionPolicy: Delete
  forProvider:
    availabilityZone: us-west-2a
    cidrBlock: 192.168.0.0/18
    mapPublicIpOnLaunch: true
    privateDnsHostnameTypeOnLaunch: ip-name
    region: us-west-2
    tags:
      crossplane-kind: subnet.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-phfgs
      crossplane-providerconfig: default
      kubernetes.io/role/elb: "1"
      networks.aws.platform.upbound.io/network-id: configuration-aws-network
    vpcId: vpc-0036481418bd747c0
    vpcIdRef:
      name: configuration-aws-network-6jtl4
    vpcIdSelector:
      matchControllerRef: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:123456789012:subnet/subnet-00ca6a5b1969198e5
    assignIpv6AddressOnCreation: false
    availabilityZone: us-west-2a
    availabilityZoneId: usw2-az1
    cidrBlock: 192.168.0.0/18
    customerOwnedIpv4Pool: ""
    enableDns64: false
    enableLniAtDeviceIndex: 0
    enableResourceNameDnsARecordOnLaunch: false
    enableResourceNameDnsAaaaRecordOnLaunch: false
    id: subnet-00ca6a5b1969198e5
    ipv6CidrBlock: ""
    ipv6CidrBlockAssociationId: ""
    ipv6Native: false
    mapCustomerOwnedIpOnLaunch: false
    mapPublicIpOnLaunch: true
    outpostArn: ""
    ownerId: "123456789012"
    privateDnsHostnameTypeOnLaunch: ip-name
    tags:
      crossplane-kind: subnet.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-phfgs
      crossplane-providerconfig: default
      kubernetes.io/role/elb: "1"
      networks.aws.platform.upbound.io/network-id: configuration-aws-network
    tagsAll:
      crossplane-kind: subnet.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-phfgs
      crossplane-providerconfig: default
      kubernetes.io/role/elb: "1"
      networks.aws.platform.upbound.io/network-id: configuration-aws-network
    vpcId: vpc-0036481418bd747c0
  conditions:
  - lastTransitionTime: "2024-08-17T11:02:44Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-17T00:19:07Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-17T00:19:06Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
