apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    crossplane.io/composition-resource-name: vpc
    crossplane.io/external-create-pending: "2024-08-17T00:17:55Z"
    crossplane.io/external-create-succeeded: "2024-08-17T00:17:55Z"
    crossplane.io/external-name: vpc-0036481418bd747c0
  creationTimestamp: "2024-08-17T00:15:48Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: configuration-aws-network-
  generation: 3
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: configuration-aws-network
    networks.aws.platform.upbound.io/network-id: configuration-aws-network
  name: configuration-aws-network-6jtl4
  ownerReferences:
  - apiVersion: aws.platform.upbound.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XNetwork
    name: configuration-aws-network
    uid: 74422427-ef9c-4d2c-bee5-3a6cfef8684d
  resourceVersion: "447194"
  uid: 15f9a18c-dc6d-42d7-ba87-a403f35ba5a4
spec:
  deletionPolicy: Delete
  forProvider:
    cidrBlock: 192.168.0.0/16
    enableDnsHostnames: true
    enableDnsSupport: true
    instanceTenancy: default
    region: us-west-2
    tags:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-6jtl4
      crossplane-providerconfig: default
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    arn: arn:aws:ec2:us-west-2:123456789012:vpc/vpc-0036481418bd747c0
    assignGeneratedIpv6CidrBlock: false
    cidrBlock: 192.168.0.0/16
    defaultNetworkAclId: acl-06db95aef137a068f
    defaultRouteTableId: rtb-0af6bc45f6642a988
    defaultSecurityGroupId: sg-035ad4e2f155abaaa
    dhcpOptionsId: dopt-0c388774
    enableDnsHostnames: true
    enableDnsSupport: true
    enableNetworkAddressUsageMetrics: false
    id: vpc-0036481418bd747c0
    instanceTenancy: default
    ipv6AssociationId: ""
    ipv6CidrBlock: ""
    ipv6CidrBlockNetworkBorderGroup: ""
    ipv6IpamPoolId: ""
    ipv6NetmaskLength: 0
    mainRouteTableId: rtb-0af6bc45f6642a988
    ownerId: "123456789012"
    tags:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-6jtl4
      crossplane-providerconfig: default
    tagsAll:
      Name: configuration-aws-network
      crossplane-kind: vpc.ec2.aws.upbound.io
      crossplane-name: configuration-aws-network-6jtl4
      crossplane-providerconfig: default
  conditions:
  - lastTransitionTime: "2024-08-17T01:50:33Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-17T00:18:10Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-08-17T00:18:07Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation
