apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: namespace-team-3
    crossplane.io/external-create-pending: "2024-08-17T18:09:24Z"
    crossplane.io/external-create-succeeded: "2024-08-17T18:09:24Z"
    crossplane.io/external-name: example-59mdb
  creationTimestamp: "2024-08-17T18:09:23Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generateName: example-
  generation: 2
  labels:
    crossplane.io/claim-name: ""
    crossplane.io/claim-namespace: ""
    crossplane.io/composite: example
  name: example-59mdb
  ownerReferences:
  - apiVersion: k8s.example.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: XTenant
    name: example
    uid: fc82b6af-8321-4e9a-855a-ce3ff7a770f6
  resourceVersion: "487581"
  uid: 5720f9d9-1e66-4a1c-80a6-1a0717f0813b
spec:
  deletionPolicy: Delete
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: team-3
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
  readiness:
    policy: SuccessfulCreate
  watch: false
status:
  atProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        annotations:
          kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Namespace","metadata":{"name":"team-3"}}'
        creationTimestamp: "2024-08-17T18:09:24Z"
        labels:
          kubernetes.io/metadata.name: team-3
        managedFields:
        - apiVersion: v1
          fieldsType: FieldsV1
          fieldsV1:
            f:metadata:
              f:annotations:
                .: {}
                f:kubectl.kubernetes.io/last-applied-configuration: {}
              f:labels:
                .: {}
                f:kubernetes.io/metadata.name: {}
          manager: crossplane-kubernetes-provider
          operation: Update
          time: "2024-08-17T18:09:24Z"
        name: team-3
        resourceVersion: "487574"
        uid: 12e27d3c-cfae-4435-998a-0792daa91d5a
      spec:
        finalizers:
        - kubernetes
      status:
        phase: Active
  conditions:
  - lastTransitionTime: "2024-08-17T18:09:23Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-08-17T18:09:24Z"
    reason: Available
    status: "True"
    type: Ready
